defaults:
  - experiment: base_experiment
  # - algorithm: ???
  # - task: ???
  # - model: layers/mlp
  - algorithm: mappo
  - task: vmas/simple_tag_pos
  - model: layers/gnn
  - model@critic_model: layers/mlp
  - _self_

seed: 0
